version: "3.7"
# image: flink:latest
# image: pyflink/pyflink:1.11.0
# image: pyflink/playgrounds:1.13.0-rc2
services:
  flink-jobmanager:
    build:
      dockerfile: Dockerfile
    entrypoint: ["/docker-entrypoint.sh", "jobmanager"]
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - |
        FLINK_PROPERTIES=
          taskmanager.numberOfTaskSlots: 5
      # - ENABLE_BUILT_IN_PLUGINS=flink-connector-files-1.16.0.jar
    volumes:
      - ./src:/opt/flink/src
#    networks:
#      flink-network:
#        ipv4_address: 10.5.0.5

  flink-taskmanager:
    build:
      dockerfile: Dockerfile
    entrypoint: ["/docker-entrypoint.sh", "taskmanager"]
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - |
        FLINK_PROPERTIES=
          taskmanager.numberOfTaskSlots: 5
      # - ENABLE_BUILT_IN_PLUGINS=flink-connector-files-1.16.0.jar
    volumes:
      - ./src:/opt/flink/src
#    networks:
#      flink-network:
#        ipv4_address: 10.5.0.6

#networks:
#  flink-network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.5.0.0/16
#          gateway: 10.5.0.1